Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-elo-static1-websit2e-bucket
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
BucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref s3Bucket
    PolicyDocument:
      Statement:
      - Sid: PublicReadGetObject
        Effect: Allow
        Principal: '*'
        Action: s3:GetObject
        Resources: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]
